apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-next
  labels:
    app: order-service-next
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service-next
  template:
    metadata:
      labels:
        app: order-service-next
    # Specifies a pod with one container
    spec:
      containers:
        - name: order-service-next
          image: order-api:vnext
          imagePullPolicy: Never # > This option is set to never to use local images.
          ports:
            - name: web
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-next

spec:
  ports:
    - name: web
      port: 80
      targetPort: web

  selector:
    app: order-service-next
