apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prodtest-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prodtestapi-latest
            port:
              name: web