name: Domain Common

on:
  pull_request:
    branches:
      - main
      - 'sprint/**'

jobs:
  run-checks:
    uses: brdv/prodtest-demo/.github/workflows/service-check.yaml@sprint/4
    with:
      project_dir: 'src/Common/Domain.Common'
      test_project: 'src/Common/Domain.Common.Tests/'
