name: Running checks for OrderService

on:
  pull_request:
    branches:
      - main
      - 'sprint/**'

jobs:
  order-service-checks:
    uses: brdv/prodtest-demo/.github/workflows/service-check.yaml@fix/split-order-kitchen-service
  with:
    project_dir: 'src/Services/Order/Order.API'
    test_project: 'src/Services/Order/Order.API.Tests/'
